sudo: required
services:
   - docker

before_install:
   - sudo gem install bundler
   - docker build -t vijaynza/docker-react -f Dockerfile.dev .

script:
  - docker run vijaynza/docker-react npm run test -- --coverage
