sudo: required
services:
  - docker

before_install:
  - docker build -t vijaynza/docker-react -f Dockerfile.dev .

install: travis_wait 30 npm install

script:
  - travis_wait 30 docker run vijaynza/docker-react npm run test -- --coverage
